In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [4]:
df =pd.read_csv('500hits.csv',encoding='latin-1')

In [5]:
df.head()

         PLAYER  YRS     G     AB     R     H  ...    BB    SO   SB   CS     BA  HOF
0       Ty Cobb   24  3035  11434  2246  4189  ...  1249   357  892  178  0.366    1
1   Stan Musial   22  3026  10972  1949  3630  ...  1599   696   78   31  0.331    1
2  Tris Speaker   22  2789  10195  1882  3514  ...  1381   220  432  129  0.345    1
3   Derek Jeter   20  2747  11195  1923  3465  ...  1082  1840  358   97  0.310    1
4  Honus Wagner   21  2792  10430  1736  3430  ...   963   327  722   15  0.329    1

[5 rows x 16 columns]

In [6]:
df.tail()

             PLAYER  YRS     G    AB     R  ...    SO   SB   CS     BA  HOF
460        Jim Wynn   15  1920  6653  1105  ...  1427  225  101  0.250    0
461    Jorge Posada   17  1829  6092   900  ...  1453   20   21  0.273    0
462  Brady Anderson   15  1834  6499  1062  ...  1190  315  100  0.256    0
463    Cookie Rojas   16  1822  6309   714  ...   489   74   68  0.263    0
464   Mickey Rivers   15  1468  5629   785  ...   471  267   90  0.295    0

[5 rows x 16 columns]

In [9]:
X=df.drop(columns=['PLAYER','HOF'])
y=df['HOF']
X.head()

   YRS     G     AB     R     H   2B  ...   RBI    BB    SO   SB   CS     BA
0   24  3035  11434  2246  4189  724  ...   726  1249   357  892  178  0.366
1   22  3026  10972  1949  3630  725  ...  1951  1599   696   78   31  0.331
2   22  2789  10195  1882  3514  792  ...   724  1381   220  432  129  0.345
3   20  2747  11195  1923  3465  544  ...  1311  1082  1840  358   97  0.310
4   21  2792  10430  1736  3430  640  ...     0   963   327  722   15  0.329

[5 rows x 14 columns]

In [13]:
print("X",X.shape)
print("y",y.shape)
print(y)
print("-"*50)
print(y.head())

X (465, 14)
y (465,)
0      1
1      1
2      1
3      1
4      1
      ..
460    0
461    0
462    0
463    0
464    0
Name: HOF, Length: 465, dtype: int64
--------------------------------------------------
0    1
1    1
2    1
3    1
4    1
Name: HOF, dtype: int64

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=11,test_size=0.2)
X_train.shape

(372, 14)

In [15]:
X_test.shape

(93, 14)

In [17]:
X_train.describe()

              YRS            G  ...          CS          BA
count  372.000000   372.000000  ...  372.000000  372.000000
mean    17.010753  2046.521505  ...   58.986559    0.289164
std      2.662486   351.232903  ...   49.322224    0.021069
min     11.000000  1331.000000  ...    0.000000    0.246000
25%     15.000000  1797.500000  ...   23.000000    0.274000
50%     17.000000  1992.000000  ...   52.000000    0.288000
75%     19.000000  2245.500000  ...   84.000000    0.300250
max     26.000000  3308.000000  ...  335.000000    0.366000

[8 rows x 14 columns]

In [18]:
X_train.describe().round(2)

          YRS        G        AB        R  ...       SO       SB      CS      BA
count  372.00   372.00    372.00   372.00  ...   372.00   372.00  372.00  372.00
mean    17.01  2046.52   7526.08  1154.13  ...   850.32   196.93   58.99    0.29
std      2.66   351.23   1302.41   291.31  ...   472.92   185.59   49.32    0.02
min     11.00  1331.00   4981.00   651.00  ...     0.00     7.00    0.00    0.25
25%     15.00  1797.50   6507.50   936.00  ...   448.00    64.50   23.00    0.27
50%     17.00  1992.00   7237.00  1099.00  ...   844.00   141.00   52.00    0.29
75%     19.00  2245.50   8198.25  1305.00  ...  1234.25   285.50   84.00    0.30
max     26.00  3308.00  12364.00  2295.00  ...  1936.00  1406.00  335.00    0.37

[8 rows x 14 columns]

In [19]:
X_test.describe().round(3)

          YRS         G         AB  ...       SB       CS      BA
count  93.000    93.000     93.000  ...   93.000   93.000  93.000
mean   17.204  2057.409   7452.968  ...  191.817   54.473   0.287
std     3.154   368.580   1265.371  ...  166.926   42.508   0.022
min    11.000  1399.000   5472.000  ...    8.000    0.000   0.248
25%    15.000  1820.000   6622.000  ...   61.000   15.000   0.272
50%    17.000  1997.000   7359.000  ...  137.000   50.000   0.285
75%    19.000  2282.000   8096.000  ...  271.000   83.000   0.299
max    25.000  2850.000  10876.000  ...  744.000  173.000   0.340

[8 rows x 14 columns]

AttributeError: 'float' object has no attribute 'round'